_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 8
epochs:
    value: 10
learning_rate:
    value: 0.0001
model:
    value: ENet
optimizer:
    value: Adam
